\copy employee from 'employee.csv' CSV HEADER;
\copy customer from  'customer.csv' CSV HEADER;
\copy orders from 'orders.csv' CSV HEADER;
\copy ingredients from 'ingredients.csv' CSV HEADER;
\copy menu_item from 'menu_item.csv' CSV HEADER;
\copy drink from 'drink.csv' CSV HEADER;
\copy topping from 'topping.csv' CSV HEADER;
\copy drink_topping from 'drink_topping.csv' CSV HEADER;
\copy menu_ingredients_mapper from 'menu_ingredients_mapper.csv' CSV HEADER;